from __future__ import annotations

from backend.app.runs.status import RunStatus

ACTIVE_RUN_STATUS_VALUES = (
    RunStatus.QUEUED.value,
    RunStatus.RUNNING.value,
    RunStatus.WAITING_RUNTIME.value,
    RunStatus.WAITING_APPROVAL.value,
)

CAPACITY_CONSUMING_RUN_STATUS_VALUES = ACTIVE_RUN_STATUS_VALUES
WORKLOAD_RUN_STATUS_VALUES = ACTIVE_RUN_STATUS_VALUES

STALE_RECOVERABLE_RUN_STATUS_VALUES = (
    RunStatus.QUEUED.value,
    RunStatus.RUNNING.value,
    RunStatus.WAITING_RUNTIME.value,
)

ACTIVE_RUN_STATUSES = frozenset(ACTIVE_RUN_STATUS_VALUES)
CAPACITY_CONSUMING_RUN_STATUSES = frozenset(CAPACITY_CONSUMING_RUN_STATUS_VALUES)
WORKLOAD_RUN_STATUSES = frozenset(WORKLOAD_RUN_STATUS_VALUES)
STALE_RECOVERABLE_RUN_STATUSES = frozenset(STALE_RECOVERABLE_RUN_STATUS_VALUES)
