from __future__ import annotations

from collections.abc import Callable
from typing import Protocol, TypedDict
from uuid import UUID

from redis import Redis

from backend.app.redis.keys import RedisKeyBuilder
from backend.app.workers.jobs import JobPayload


class ProcessingEntry(TypedDict):
    payload: str
    job: JobPayload


class QueueStorage(Protocol):
    """Shared storage contract required by the queue's implementation components."""

    @property
    def redis(self) -> Redis[str]: ...

    @property
    def keys(self) -> RedisKeyBuilder: ...

    @property
    def queue_name(self) -> str: ...

    @property
    def blocking_timeout_seconds(self) -> int: ...

    @property
    def visibility_timeout_seconds(self) -> int: ...

    @property
    def retry_base_delay_seconds(self) -> float: ...

    @property
    def retry_max_delay_seconds(self) -> float: ...

    def _serialize(self, job: JobPayload) -> str: ...
    def _deserialize(self, raw_payload: bytes | str) -> JobPayload: ...
    def _processing_key(self) -> str: ...
    def _retry_key(self) -> str: ...
    def _serialize_processing_entry(self, raw_payload: bytes | str) -> str: ...
    def _deserialize_processing_entry(self, raw_entry: bytes | str) -> ProcessingEntry: ...
    def _remove_processing_job(self, job_id: UUID) -> JobPayload | None: ...
    def _lease_raw_job(self, queue_key: str, raw_payload: bytes | str) -> bool: ...
    def _pop_best_matching(
        self, predicate: Callable[[JobPayload], bool], *, scan_limit: int = 50,
    ) -> JobPayload | None: ...
    def reclaim_due_retries(
        self, *, limit: int = 100, now: float | None = None,
    ) -> list[JobPayload]: ...
    def _retry_delay(self, job: JobPayload, *, delay_seconds: float | None) -> float: ...
